# Generated by Django 4.2.6 on 2024-05-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
