# Generated by Django 4.2.6 on 2024-05-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batting_score", models.IntegerField()),
                ("batting_wickets", models.IntegerField()),
                ("batting_overs", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_matches",
                        to="tournament.match",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_matches",
                        to="tournament.team",
                    ),
                ),
            ],
        ),
    ]
